version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Build Docker image
          command: docker build -t flask-app .

      - run:
          name: Test Application
          command: docker run -p 5000:5000 flask-app python -m unittest

workflows:
  version: 2
  build:
    jobs:
      - build